# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('nro_cheque', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoviemientoDiario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nro_ingreso', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descrip', models.CharField(max_length=100)),
                ('importe', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parte_diario_caja.MoviemientoDiario'),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parte_diario_caja.Servicio'),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica'),
        ),
    ]
