# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parte_diario_caja', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientodiario',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaGenerica'),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parte_diario_caja.MovimientoDiario'),
        ),
    ]
