# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte_diario_caja', '0002_auto_20181002_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueodiario',
            name='turno',
            field=models.CharField(choices=[(b'Ma\xc3\xb1ana', 'Ma\xf1ana'), (b'Tarde', 'Tarde')], max_length=10, null=True),
        ),
    ]
