# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parte_diario_caja', '0003_arqueodiario_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientodiario',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
