# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parte_diario_caja', '0004_auto_20190618_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientodiario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
