# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-26 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parte_diario_caja', '0006_auto_20190626_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arqueodiario',
            name='realizado',
        ),
        migrations.AlterField(
            model_name='movimientodiario',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2019, 6, 26, 18, 34, 5, 753163)),
        ),
    ]
