# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 13:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('resultado', models.CharField(choices=[(b'NEGATIVO', 'NEGATIVO'), (b'POSITIVO', 'POSITIVO')], max_length=15)),
                ('categoria', models.CharField(choices=[(b'PRODUCTOR', 'PRODUCTOR'), (b'PARTICULAR', 'PARTICULAR')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AplazoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplazo', models.DateField(default=django.utils.timezone.now)),
                ('motivo_aplazo', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ControlAntirrabico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_suceso', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DisposicionCriaderoCerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disposicion', models.DateField()),
                ('nro_disposicion', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Esterilizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anticonceptivos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('partos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ultimo_celo', models.DateField(blank=True, null=True)),
                ('turno', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pelaje', models.CharField(max_length=50)),
                ('categoria_mascota', models.CharField(choices=[(b'CANINO', 'CANINO'), (b'FELINO', 'FELINO')], max_length=6)),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[(b'MACHO', 'MACHO'), (b'HEMBRA', 'HEMBRA')], max_length=15)),
                ('nacimiento_fecha', models.DateField(blank=True, null=True)),
                ('baja', models.BooleanField(default=False)),
                ('esterilizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_patente', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_garrapaticida', models.DateField(null=True)),
                ('fecha_antiparasitario', models.DateField(null=True)),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Porcino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinto', models.BigIntegerField(unique=True)),
                ('categoria_porcino', models.CharField(choices=[(b'LECHON', 'LECHON'), (b'PORKER', 'PORKER'), (b'ADULTO', 'ADULTO')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RetiroEntregaAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('patentado', models.BooleanField(default=False)),
                ('tramite', models.CharField(choices=[(b'ENTREGA', 'ENTREGA'), (b'RETIRO', 'RETIRO')], max_length=10)),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCriaderoCerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now)),
                ('categoria_criadero', models.CharField(choices=[(b'CONSUMO FAMILIAR', 'CONSUMO FAMILIAR'), (b'MINI EMPRENDIMIENTO PRODUCTIVO PORCINO', 'MINI EMPRENDIMIENTO PRODUCTIVO PORCINO'), (b'ESTABLECIMIENTO DE CRIA PORCINA', 'ESTABLECIMIENTO DE CRIA PORCINA'), (b'OTROS', 'OTROS')], max_length=50)),
                ('observaciones', models.TextField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='En curso', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, max_length=200, null=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.ControlAntirrabico')),
            ],
        ),
    ]
