# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nro_ingreso', models.BigIntegerField()),
                ('procedencia', models.CharField(max_length=50)),
                ('resultado', models.CharField(choices=[(b'Negativo', 'Negativo'), (b'Positivo', 'Positivo')], max_length=15)),
                ('categoria', models.CharField(choices=[(b'Productor', 'Productor'), (b'Particular', 'Particular')], max_length=15)),
                ('interesado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interesado', to='personas.PersonaFisica')),
                ('medico_veterinario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico_veterinario', to='personas.PersonaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='AplazoSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplazo', models.DateField(default=django.utils.timezone.now)),
                ('motivo_aplazo', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_antiparasitario', models.DateField()),
                ('fecha_garrapaticida', models.DateField()),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ControlAntirrabico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_suceso', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('mordido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mordido', to='personas.PersonaFisica')),
                ('responsable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='personas.PersonaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='DisposicionCriaderoCerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disposicion', models.DateField()),
                ('nro_disposicion', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Esterilizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.TimeField()),
                ('interesado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaGenerica')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pelaje', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('sexo', models.CharField(blank=True, choices=[(b'Macho', 'Macho'), (b'Hembra', 'Hembra')], max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animales.Mascota')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Porcino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinto', models.BigIntegerField(unique=True)),
                ('categoria_porcino', models.CharField(choices=[(b'Lechon', 'Lechon'), (b'Porker', 'Porker'), (b'Adulto', 'Adulto')], max_length=6)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Analisis')),
            ],
        ),
        migrations.CreateModel(
            name='RetiroEntregaAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('baja', models.BooleanField(default=False)),
                ('interesado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaGenerica')),
                ('mascota', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animales.Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCriaderoCerdos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now)),
                ('categoria_criadero', models.CharField(choices=[(b'CONSUMO FAMILIAR', 'CONSUMO FAMILIAR'), (b'MINI EMPRENDIMIENTO PRODUCTIVO PORCINO', 'MINI EMPRENDIMIENTO PRODUCTIVO PORCINO'), (b'ESTABLECIMIENTO DE CRIA PORCINA', 'ESTABLECIMIENTO DE CRIA PORCINA')], max_length=50)),
                ('domicilio_criadero', models.CharField(max_length=50)),
                ('estado', models.CharField(default='En curso', max_length=10)),
                ('interesado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica')),
            ],
        ),
        migrations.AddField(
            model_name='esterilizacion',
            name='mascota',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animales.Mascota'),
        ),
        migrations.AddField(
            model_name='disposicioncriaderocerdos',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animales.SolicitudCriaderoCerdos'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='patente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Patente'),
        ),
        migrations.AddField(
            model_name='aplazosolicitud',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animales.SolicitudCriaderoCerdos'),
        ),
    ]
