# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nro_ingreso', models.BigIntegerField()),
                ('procedencia', models.CharField(max_length=50)),
                ('resultado', models.CharField(choices=[(b'Negativo', 'Negativo'), (b'Positivo', 'Positivo')], max_length=15)),
                ('categoria', models.CharField(choices=[(b'Productor', 'Productor'), (b'Particular', 'Particular')], max_length=15)),
                ('interesado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interesado', to='personas.PersonaFisica')),
                ('medico_veterinario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico_veterinario', to='personas.PersonaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinto', models.BigIntegerField(unique=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Analisis')),
            ],
        ),
    ]
