# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcriaderocerdos',
            name='domicilio_criadero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.DomicilioRural'),
        ),
        migrations.AddField(
            model_name='solicitudcriaderocerdos',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica'),
        ),
        migrations.AddField(
            model_name='retiroentregaanimal',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaGenerica'),
        ),
        migrations.AddField(
            model_name='retiroentregaanimal',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animales.Mascota'),
        ),
        migrations.AddField(
            model_name='porcino',
            name='analisis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Analisis'),
        ),
        migrations.AddField(
            model_name='patente',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Mascota'),
        ),
        migrations.AddField(
            model_name='patente',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica'),
        ),
        migrations.AddField(
            model_name='esterilizacion',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaGenerica'),
        ),
        migrations.AddField(
            model_name='esterilizacion',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animales.Mascota'),
        ),
        migrations.AddField(
            model_name='disposicioncriaderocerdos',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='animales.SolicitudCriaderoCerdos'),
        ),
        migrations.AddField(
            model_name='controlantirrabico',
            name='mordido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mordido', to='personas.PersonaFisica'),
        ),
        migrations.AddField(
            model_name='controlantirrabico',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='personas.PersonaFisica'),
        ),
        migrations.AddField(
            model_name='aplazosolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.SolicitudCriaderoCerdos'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesado', to='personas.PersonaFisica'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='medico_veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_veterinario', to='personas.PersonalPropio'),
        ),
        migrations.AddField(
            model_name='analisis',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Localidad'),
        ),
    ]
