# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiroentregaanimal',
            name='patentado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='retiroentregaanimal',
            name='tramite',
            field=models.CharField(choices=[(b'ENTREGA', 'ENTREGA'), (b'RETIRO', 'RETIRO')], max_length=10),
        ),
    ]
