# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesado', to='personas.PersonaFisica'),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='medico_veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_veterinario', to='personas.PersonaFisica'),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='procedencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Localidad'),
        ),
        migrations.AlterField(
            model_name='controlantirrabico',
            name='mordido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mordido', to='personas.PersonaFisica'),
        ),
        migrations.AlterField(
            model_name='controlantirrabico',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='personas.PersonaFisica'),
        ),
        migrations.AlterField(
            model_name='esterilizacion',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaGenerica'),
        ),
        migrations.AlterField(
            model_name='esterilizacion',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animales.Mascota'),
        ),
        migrations.AlterField(
            model_name='retiroentregaanimal',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaGenerica'),
        ),
        migrations.AlterField(
            model_name='solicitudcriaderocerdos',
            name='interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica'),
        ),
    ]
