# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinto', models.BigIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('Lechon', 'Lechon'), ('Porker', 'Porker'), ('Adulto', 'Adulto')], max_length=6)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.Analisis')),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='analisis',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
