# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_auto_20180804_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiroentregaanimal',
            name='patente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patente',
            name='fecha_antiparasitario',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patente',
            name='fecha_garrapaticida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retiroentregaanimal',
            name='tramite',
            field=models.CharField(choices=[(b'ENTREGA', 'ENTREGA'), (b'SACRIFICIO', 'SACRIFICIO')], max_length=10),
        ),
    ]
