# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_auto_20181002_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porcino',
            name='precinto',
            field=models.IntegerField(unique=True),
        ),
    ]
