# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-14 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_auto_20181015_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='porcino',
            name='precinto2',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
