# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-01 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0005_auto_20181114_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esterilizacion',
            name='turno',
            field=models.DateTimeField(unique=True),
        ),
    ]
