# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_auto_20180826_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='medico_veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico_veterinario', to='personas.PersonalPropio'),
        ),
    ]
