# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-29 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0007_auto_20190404_1718'),
        ('animales', '0007_auto_20190403_1018'),
    ]

    operations = [
    ]
