# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20190324_2044'),
        ('animales', '0008_merge_20190429_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='toma_muestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toma_muestra', to='personas.PersonalPropio'),
        ),
    ]
