# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-01 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_directive',
            field=models.BooleanField(default=False),
        ),
    ]
