# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecedor',
            fields=[
                ('personafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.PersonaFisica')),
                ('empresa', models.CharField(max_length=25, unique=True)),
            ],
            bases=('personas.personafisica',),
        ),
        migrations.CreateModel(
            name='Desinfeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quincena', models.CharField(choices=[(b'Primer quincena', 'Primer quincena'), (b'Segunda quincena', 'Segunda quincena')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reinspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.TimeField()),
                ('precintado', models.IntegerField()),
                ('num_certificado', models.BigIntegerField()),
                ('abastecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.Abastecedor')),
                ('primer_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_1', to='personas.PersonalPropio')),
            ],
        ),
        migrations.CreateModel(
            name='ReinspeccionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo_producto', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.Producto')),
                ('reinspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.Reinspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('dominio', models.CharField(max_length=50, unique=True)),
                ('tsa', models.BooleanField()),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica')),
            ],
        ),
        migrations.AddField(
            model_name='desinfeccion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.Vehiculo'),
        ),
    ]
