# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_y_o_transporte', models.CharField(max_length=150)),
                ('rubro', models.CharField(max_length=150)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Reinspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('turno', models.DateTimeField()),
                ('precintado', models.IntegerField()),
                ('num_certificado', models.BigIntegerField()),
                ('abastecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.Abastecedor')),
                ('primer_inspector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_1', to='personas.PersonaFisica')),
                ('segundo_inspector', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspector_2', to='personas.PersonaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='ReinspeccionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo_producto', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.Producto')),
                ('reinspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.Reinspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Tsa_Tpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abastecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.Abastecedor')),
                ('persona', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='personas.PersonaFisica')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='personas.PersonaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('dominio', models.CharField(max_length=50)),
            ],
        ),
    ]
