# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspeccion',
            name='turno',
            field=models.TimeField(),
        ),
    ]
