# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspeccion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
