# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('saneamiento_abasto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinspeccion',
            name='primer_inspector',
        ),
        migrations.AddField(
            model_name='reinspeccion',
            name='inspectores',
            field=models.ManyToManyField(to='personas.PersonalPropio'),
        ),
    ]
