# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspeccion',
            name='certificado',
            field=models.IntegerField(unique=True),
        ),
    ]
