# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-05 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('saneamiento_abasto', '0002_auto_20181005_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinspeccion',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Localidad'),
        ),
    ]
