# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-26 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0003_auto_20180826_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspeccion',
            name='importe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
