# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0004_auto_20180826_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='controldeplaga',
            name='fecha_prox_visita',
        ),
        migrations.AddField(
            model_name='visitacontrol',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.ControlDePlaga'),
        ),
    ]
