# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-14 21:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0004_auto_20181116_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950)]),
        ),
        migrations.AlterField(
            model_name='marcavehiculo',
            name='nombre',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='modelovehiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.MarcaVehiculo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.ModeloVehiculo'),
        ),
    ]
