# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-14 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0005_auto_20190114_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.ModeloVehiculo'),
        ),
    ]
