# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0005_auto_20180920_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitacontrol',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
