# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0006_auto_20190114_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinspeccion',
            name='turno',
            field=models.CharField(choices=[(b'Ma\xc3\xb1ana', 'Ma\xf1ana'), (b'Tarde', 'Tarde'), (b'Sabado', 'Sabado'), (b'Feriado', 'Feriado/Fuera de horario'), (b'Excepcion', 'Excepcion')], max_length=10),
        ),
    ]
