# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-15 19:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0007_auto_20190401_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(blank=True, null=True)),
                ('total_kg', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('importe', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_certificado', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
