# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-17 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0010_auto_20190417_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecc',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
