# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-19 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0011_detallecc_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecc',
            name='pagado',
        ),
    ]
