# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-19 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0012_remove_detallecc_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecc',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saneamiento_abasto.PeriodoCC'),
        ),
    ]
