# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-19 23:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0014_auto_20190419_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodocc',
            name='importe',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='periodocc',
            name='total_kg',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
