# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0015_auto_20190419_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecc',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saneamiento_abasto.PeriodoCC'),
        ),
    ]
