# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0016_auto_20190502_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaGenerica'),
        ),
    ]
