# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 11:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0017_auto_20190507_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='nro',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
