# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saneamiento_abasto', '0018_auto_20190515_0858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiculo',
            unique_together=set([('tipo_vehiculo', 'nro')]),
        ),
    ]
