# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-02 15:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cupo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)])),
                ('lugar', models.CharField(max_length=50)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('modificado', models.BooleanField(default=False)),
                ('calificacion', models.CharField(blank=True, choices=[(b'Sin Calificar', 'Sin Calificar'), (b'Aprobado', 'Aprobado'), (b'Desaprobado', 'Desaprobado')], max_length=15)),
                ('porcentaje_asistencia', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('rubro', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LibretaSanitaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('fecha_examen_clinico', models.DateField()),
                ('profesional_examen_clinico', models.CharField(default='', max_length=200)),
                ('lugar_examen_clinico', models.CharField(default='', max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo_libreta', models.CharField(choices=[(b'Blanca', 'BLANCA'), (b'Amarilla', 'AMARILLA'), (b'Celeste', 'CELESTE')], max_length=10)),
                ('fecha_vencimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, upload_to='libreta_curso/foto/')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreta_curso.Curso')),
            ],
        ),
    ]
