# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 09:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('cupo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('lugar', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('modificado', models.BooleanField(default=False)),
                ('nota_curso', models.CharField(blank=True, choices=[(b'Sin Calificar', 'Sin Calificar'), (b'Aprobado', 'Aprobado'), (b'Desaprobado', 'Desaprobado')], max_length=15)),
                ('porcentaje_asistencia', models.FloatField(blank=True, null=True)),
                ('nro_ingresos_varios', models.BigIntegerField(blank=True, null=True)),
                ('arancel', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreta_curso.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='LibretaSanitaria',
            fields=[
                ('nro_ingresos_varios', models.BigIntegerField(blank=True)),
                ('arancel', models.FloatField(blank=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personas.PersonaFisica')),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('fecha_examen_clinico', models.DateField()),
                ('profesional_examen_clinico', models.CharField(default='', max_length=200)),
                ('lugar_examen_clinico', models.CharField(default='', max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreta_curso.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica'),
        ),
    ]
