# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('cupo', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
                ('lugar', models.CharField(max_length=50)),
                ('horario', models.TimeField()),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField()),
                ('nota_curso', models.IntegerField(blank=True, null=True)),
                ('porcentaje_asistencia', models.FloatField(blank=True, null=True)),
                ('nro_ingresos_varios', models.BigIntegerField(blank=True, null=True)),
                ('arancel', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreta_curso.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('rubro', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cuil', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('obra_social', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibretaSanitaria',
            fields=[
                ('nro_ingresos_varios', models.BigIntegerField(blank=True)),
                ('arancel', models.FloatField(blank=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='libreta_curso.PersonaFisica')),
                ('observaciones', models.TextField(blank=True, default='', max_length=200)),
                ('fecha_examen_clinico', models.DateField()),
                ('profesional_examen_clinico', models.CharField(default='', max_length=200)),
                ('lugar_examen_clinico', models.CharField(default='', max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libreta_curso.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreta_curso.PersonaFisica'),
        ),
    ]
