# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreta_curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libretasanitaria',
            name='fecha_examen_clinico',
            field=models.DateField(),
        ),
    ]
