# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('libreta_curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libretasanitaria',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreta_curso.Curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.PersonaFisica'),
        ),
    ]
