# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreta_curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='nro_ingresos_varios',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
