# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreta_curso', '0002_auto_20170720_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='cupo',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)]),
        ),
    ]
