# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-16 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreta_curso', '0002_auto_20181002_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libretasanitaria',
            name='fecha_examen_clinico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libretasanitaria',
            name='lugar_examen_clinico',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='libretasanitaria',
            name='profesional_examen_clinico',
            field=models.CharField(max_length=200),
        ),
    ]
