# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreta_curso', '0004_auto_20190116_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='libretasanitaria',
            name='pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
