# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('rubro', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cuil', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('obra_social', models.CharField(blank=True, max_length=50)),
                ('documentacion_retirada', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
