# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=50)),
                ('nro', models.IntegerField()),
                ('dpto', models.CharField(blank=True, max_length=2, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('cp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaGenerica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('rubro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('personagenerica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.PersonaGenerica')),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('obra_social', models.CharField(blank=True, max_length=50)),
                ('documentacion_retirada', models.BooleanField(default=False)),
            ],
            bases=('personas.personagenerica',),
        ),
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('personagenerica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.PersonaGenerica')),
                ('cuil', models.CharField(max_length=20, unique=True)),
            ],
            bases=('personas.personagenerica',),
        ),
        migrations.AddField(
            model_name='personagenerica',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Domicilio'),
        ),
        migrations.AddField(
            model_name='localidad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Provincia'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Localidad'),
        ),
        migrations.CreateModel(
            name='PersonalPropio',
            fields=[
                ('personafisica_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.PersonaFisica')),
                ('rol_actuante', models.CharField(max_length=50)),
            ],
            bases=('personas.personafisica',),
        ),
        migrations.AddField(
            model_name='personafisica',
            name='nacionalidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='personas.Nacionalidad'),
        ),
    ]
