# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='nro',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
