# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20181116_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domiciliorural',
            name='chacra',
            field=models.CharField(max_length=6),
        ),
    ]
