# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20190324_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafisica',
            name='tipo_dni',
            field=models.CharField(choices=[(b'DNI', 'Documento unico'), (b'LI', 'Libreta de enrolamiento'), (b'LC', 'Libreta civica'), (b'O', 'Otro')], default='DNI', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='personafisica',
            unique_together=set([('tipo_dni', 'dni')]),
        ),
    ]
