# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20190507_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personafisica',
            name='dni',
            field=models.CharField(max_length=50),
        ),
    ]
