# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20190507_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='escalera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
