# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_domicilio_edificio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='edificio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
